In [232]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))
pd.set_option('display.max_rows', 100)
pd.set_option('display.max_columns', 500)
pd.set_option('display.max_colwidth', None)
# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/tabular-playground-series-jun-2021/sample_submission.csv
/kaggle/input/tabular-playground-series-jun-2021/train.csv
/kaggle/input/tabular-playground-series-jun-2021/test.csv

In [233]:
train_df = pd.read_csv("/kaggle/input/tabular-playground-series-jun-2021/train.csv", low_memory=False)
test = pd.read_csv("/kaggle/input/tabular-playground-series-jun-2021/test.csv", low_memory=False)
train_df.info(memory_usage="deep")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200000 entries, 0 to 199999
Data columns (total 77 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   id          200000 non-null  int64
 1   feature_0   200000 non-null  int64
 2   feature_1   200000 non-null  int64
 3   feature_2   200000 non-null  int64
 4   feature_3   200000 non-null  int64
 5   feature_4   200000 non-null  int64
 6   feature_5   200000 non-null  int64
 7   feature_6   200000 non-null  int64
 8   feature_7   200000 non-null  int64
 9   feature_8   200000 non-null  int64
 10  feature_9   200000 non-null  int64
 11  feature_10  200000 non-null  int64
 12  feature_11  200000 non-null  int64
 13  feature_12  200000 non-null  int64
 14  feature_13  200000 non-null  int64
 15  feature_14  200000 non-null  int64
 16  feature_15  200000 non-null  int64
 17  feature_16  200000 non-null  int64
 18  feature_17  200000 non-null  int64
 19  feature_18  200000 non-null  int64
 20  feature_19  200000 non-null  int64
 21  feature_20  200000 non-null  int64
 22  feature_21  200000 non-null  int64
 23  feature_22  200000 non-null  int64
 24  feature_23  200000 non-null  int64
 25  feature_24  200000 non-null  int64
 26  feature_25  200000 non-null  int64
 27  feature_26  200000 non-null  int64
 28  feature_27  200000 non-null  int64
 29  feature_28  200000 non-null  int64
 30  feature_29  200000 non-null  int64
 31  feature_30  200000 non-null  int64
 32  feature_31  200000 non-null  int64
 33  feature_32  200000 non-null  int64
 34  feature_33  200000 non-null  int64
 35  feature_34  200000 non-null  int64
 36  feature_35  200000 non-null  int64
 37  feature_36  200000 non-null  int64
 38  feature_37  200000 non-null  int64
 39  feature_38  200000 non-null  int64
 40  feature_39  200000 non-null  int64
 41  feature_40  200000 non-null  int64
 42  feature_41  200000 non-null  int64
 43  feature_42  200000 non-null  int64
 44  feature_43  200000 non-null  int64
 45  feature_44  200000 non-null  int64
 46  feature_45  200000 non-null  int64
 47  feature_46  200000 non-null  int64
 48  feature_47  200000 non-null  int64
 49  feature_48  200000 non-null  int64
 50  feature_49  200000 non-null  int64
 51  feature_50  200000 non-null  int64
 52  feature_51  200000 non-null  int64
 53  feature_52  200000 non-null  int64
 54  feature_53  200000 non-null  int64
 55  feature_54  200000 non-null  int64
 56  feature_55  200000 non-null  int64
 57  feature_56  200000 non-null  int64
 58  feature_57  200000 non-null  int64
 59  feature_58  200000 non-null  int64
 60  feature_59  200000 non-null  int64
 61  feature_60  200000 non-null  int64
 62  feature_61  200000 non-null  int64
 63  feature_62  200000 non-null  int64
 64  feature_63  200000 non-null  int64
 65  feature_64  200000 non-null  int64
 66  feature_65  200000 non-null  int64
 67  feature_66  200000 non-null  int64
 68  feature_67  200000 non-null  int64
 69  feature_68  200000 non-null  int64
 70  feature_69  200000 non-null  int64
 71  feature_70  200000 non-null  int64
 72  feature_71  200000 non-null  int64
 73  feature_72  200000 non-null  int64
 74  feature_73  200000 non-null  int64
 75  feature_74  200000 non-null  int64
 76  target      200000 non-null  object
dtypes: int64(76), object(1)
memory usage: 128.2 MB

We can see that all the columns have non null values so no worries

In [234]:
train_df.head(10)

,id,feature_0,feature_1,feature_2,feature_3,feature_4,feature_5,feature_6,feature_7,feature_8,feature_9,feature_10,feature_11,feature_12,feature_13,feature_14,feature_15,feature_16,feature_17,feature_18,feature_19,feature_20,feature_21,feature_22,feature_23,feature_24,feature_25,feature_26,feature_27,feature_28,feature_29,feature_30,feature_31,feature_32,feature_33,feature_34,feature_35,feature_36,feature_37,feature_38,feature_39,feature_40,feature_41,feature_42,feature_43,feature_44,feature_45,feature_46,feature_47,feature_48,feature_49,feature_50,feature_51,feature_52,feature_53,feature_54,feature_55,feature_56,feature_57,feature_58,feature_59,feature_60,feature_61,feature_62,feature_63,feature_64,feature_65,feature_66,feature_67,feature_68,feature_69,feature_70,feature_71,feature_72,feature_73,feature_74,target
0,0,0,0,6,1,0,0,0,0,7,0,0,0,3,0,1,0,0,3,3,1,0,2,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,11,0,0,0,0,0,9,0,0,0,0,0,0,3,0,1,3,0,0,0,0,0,0,0,1,1,0,0,3,0,0,0,0,0,0,2,0,0,Class_6
1,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,2,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,0,0,0,0,0,0,1,0,Class_6
2,2,0,0,0,0,0,1,0,3,0,0,1,0,0,0,0,0,0,0,0,5,4,0,0,0,0,0,0,0,0,1,0,0,0,0,2,0,0,5,0,5,0,1,0,0,0,1,0,0,1,0,7,0,1,1,0,3,4,0,0,1,3,0,2,0,0,8,0,0,0,0,1,0,0,0,0,Class_2
3,3,0,0,7,0,1,5,2,2,0,1,2,0,5,0,0,4,0,0,22,2,1,0,0,0,0,3,0,37,0,1,3,13,0,10,0,3,1,1,0,7,0,0,2,0,1,0,0,0,0,0,0,10,0,0,25,1,0,1,2,0,2,0,7,0,0,0,0,4,0,2,2,0,4,3,0,Class_8
4,4,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,2,0,5,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,Class_2
5,5,0,15,0,0,0,1,0,0,0,2,0,2,0,1,0,1,0,0,0,7,1,0,0,0,2,0,2,0,0,0,1,0,0,0,0,1,0,0,0,10,0,0,2,0,0,1,0,1,2,0,0,0,3,0,1,0,2,0,2,0,0,3,2,0,1,0,0,0,0,0,0,0,0,0,0,Class_8
6,6,0,1,2,1,0,2,0,0,0,2,1,1,5,0,0,0,3,0,3,12,4,0,11,3,0,1,3,1,0,0,3,2,0,0,0,0,0,0,0,0,3,1,0,7,0,0,0,0,1,0,0,1,0,3,36,0,0,0,0,5,0,0,0,0,0,0,1,2,0,2,0,1,0,0,0,Class_6
7,7,2,3,5,0,0,1,1,2,10,0,0,0,0,3,6,1,0,1,0,8,4,4,0,5,1,5,1,0,1,0,8,3,1,0,3,4,0,2,1,3,0,1,0,7,1,0,3,1,0,6,3,42,1,4,6,16,6,0,1,1,0,1,1,0,0,1,8,0,0,0,0,2,3,60,0,Class_3
8,8,1,0,0,35,6,2,2,0,3,1,6,0,0,0,7,0,0,0,0,5,1,0,0,0,3,4,1,1,0,1,0,0,1,0,1,31,0,0,0,0,0,0,8,0,2,0,0,0,0,0,0,0,1,0,1,0,3,7,1,2,0,0,1,0,6,0,0,37,0,5,4,1,0,0,0,Class_2
9,9,0,0,0,0,0,0,0,0,0,0,1,0,0,2,0,0,0,0,0,6,3,0,0,0,0,7,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,4,0,4,1,1,0,0,0,0,0,1,0,0,0,1,0,0,0,0,10,0,Class_8

In [235]:
train_df["target"].unique() # There are total of 9 classes

array(['Class_6', 'Class_2', 'Class_8', 'Class_3', 'Class_1', 'Class_5',
       'Class_7', 'Class_9', 'Class_4'], dtype=object)

In [236]:
Summary = pd.DataFrame(train_df.dtypes, columns=['Dtype'])
Summary["max"] = train_df.max()
Summary["min"] = train_df.min()
Summary["Null"] = train_df.isnull().sum() # to get null values
Summary["First"] = train_df.iloc[0] # to get first value
Summary["Second"] = train_df.iloc[1] # to get second value
Summary

             Dtype      max      min  Null    First   Second
id           int64   199999        0     0        0        1
feature_0    int64       61        0     0        0        0
feature_1    int64       51        0     0        0        0
feature_2    int64       64        0     0        6        0
feature_3    int64       70        0     0        1        0
feature_4    int64       38        0     0        0        0
feature_5    int64       76        0     0        0        0
feature_6    int64       43        0     0        0        0
feature_7    int64       30        0     0        0        0
feature_8    int64       38        0     0        7        0
feature_9    int64       72        0     0        0        0
feature_10   int64       33        0     0        0        0
feature_11   int64       46        0     0        0        0
feature_12   int64       37        0     0        3        1
feature_13   int64       43        0     0        0        0
feature_14   int64       32        0     0        1        0
feature_15   int64      121        0     0        0        0
feature_16   int64       27        0     0        0        0
feature_17   int64       14        0     0        3        0
feature_18   int64       22        0     0        3        0
feature_19   int64      263        0     0        1        0
feature_20   int64       30        0     0        0        0
feature_21   int64       33        0     0        2        0
feature_22   int64      123        0     0        0        0
feature_23   int64       22        0     0        0        0
feature_24   int64       69        0     0        0        0
feature_25   int64      149        0     0        0        0
feature_26   int64       24        0     0        0        0
feature_27   int64       84        0     0        0        0
feature_28   int64      105        0     0        1        1
feature_29   int64       84        0     0        0        0
feature_30   int64       22        0     0        0        0
feature_31   int64       39        0     0        1        0
feature_32   int64       78        0     0        0        0
feature_33   int64       41        0     0        0        0
feature_34   int64       36        0     0        0        0
feature_35   int64       41        0     0        0        1
feature_36   int64       42        0     0        0        0
feature_37   int64       34        0     0       11        0
feature_38   int64       41        0     0        0        0
feature_39   int64       49        0     0        0        0
feature_40   int64       81        0     0        0        0
feature_41   int64       73        0     0        0        0
feature_42   int64       53        0     0        0        0
feature_43   int64       63        0     0        9        2
feature_44   int64       27        0     0        0        0
feature_45   int64       30        0     0        0        0
feature_46   int64      117        0     0        0        1
feature_47   int64       97        0     0        0        0
feature_48   int64       40        0     0        0        0
feature_49   int64       38        0     0        0        0
feature_50   int64       56        0     0        3        0
feature_51   int64       73        0     0        0        0
feature_52   int64       38        0     0        1        0
feature_53   int64       36        0     0        3        0
feature_54   int64      104        0     0        0        0
feature_55   int64       76        0     0        0        0
feature_56   int64       46        0     0        0        0
feature_57   int64       31        0     0        0        0
feature_58   int64       30        0     0        0        0
feature_59   int64      352        0     0        0        0
feature_60   int64      231        0     0        0        0
feature_61   int64       80        0     0        1        0
feature_62   int64      102        0     0        1        0
feature_63   int64       80        0     0        0        0
feature_64   int64       25        0     0        0        0
feature_65   int64       54        0     0        3        0
feature_66   int64       24        0     0        0        2
feature_67   int64       79        0     0        0        0
feature_68   int64       55        0     0        0        0
feature_69   int64       65        0     0        0        0
feature_70   int64       67        0     0        0        0
feature_71   int64       30        0     0        0        0
feature_72   int64       61        0     0        2        0
feature_73   int64      130        0     0        0        1
feature_74   int64       52        0     0        0        0
target      object  Class_9  Class_1     0  Class_6  Class_6

Since the values are at diff scales, we need to deal with scaling.

In [237]:
train_df = train_df.drop(["id"], axis = 1)

In [238]:
target = train_df["target"]

In [239]:
train_df = train_df.drop(["target"], axis = 1)

We can see that there are 200,000 values in here which are alot

In [240]:
test = test.drop(["id"], axis = 1)

In [241]:
values, counts = np.unique(target, return_counts=True)

In [242]:
values

array(['Class_1', 'Class_2', 'Class_3', 'Class_4', 'Class_5', 'Class_6',
       'Class_7', 'Class_8', 'Class_9'], dtype=object)

In [243]:
res = (counts/len(target)) * 100
print(res)

[ 4.559  12.2155  7.399   2.352   1.532  25.9055  7.3845 25.8815 12.771 ]

We can see that the values are not evenly distributed so we need to split the data carefully

In [244]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier

X_train, X_test, y_train, y_test = train_test_split(train_df, target, test_size = 0.2, stratify=target, random_state = 123)

Checking whether straification worked?

In [245]:
values, counts = np.unique(y_train, return_counts=True)
print(values)
print(counts)
res = (counts/len(y_train)) * 100
print(res)

['Class_1' 'Class_2' 'Class_3' 'Class_4' 'Class_5' 'Class_6' 'Class_7'
 'Class_8' 'Class_9']
[ 7294 19545 11838  3763  2451 41449 11815 41411 20434]
[ 4.55875  12.215625  7.39875   2.351875  1.531875 25.905625  7.384375
 25.881875 12.77125 ]

In [246]:
values, counts = np.unique(y_test, return_counts=True)
print(values)
print(counts)
res = (counts/len(y_test)) * 100
print(res)

['Class_1' 'Class_2' 'Class_3' 'Class_4' 'Class_5' 'Class_6' 'Class_7'
 'Class_8' 'Class_9']
[ 1824  4886  2960   941   613 10362  2954 10352  5108]
[ 4.56   12.215   7.4     2.3525  1.5325 25.905   7.385  25.88   12.77  ]

In [247]:
enc = LabelEncoder()
y_train = enc.fit_transform(y_train)
y_test = enc.transform(y_test)    
# test = enc.transform(test)

In [248]:
train_df.columns

Index(['feature_0', 'feature_1', 'feature_2', 'feature_3', 'feature_4',
       'feature_5', 'feature_6', 'feature_7', 'feature_8', 'feature_9',
       'feature_10', 'feature_11', 'feature_12', 'feature_13', 'feature_14',
       'feature_15', 'feature_16', 'feature_17', 'feature_18', 'feature_19',
       'feature_20', 'feature_21', 'feature_22', 'feature_23', 'feature_24',
       'feature_25', 'feature_26', 'feature_27', 'feature_28', 'feature_29',
       'feature_30', 'feature_31', 'feature_32', 'feature_33', 'feature_34',
       'feature_35', 'feature_36', 'feature_37', 'feature_38', 'feature_39',
       'feature_40', 'feature_41', 'feature_42', 'feature_43', 'feature_44',
       'feature_45', 'feature_46', 'feature_47', 'feature_48', 'feature_49',
       'feature_50', 'feature_51', 'feature_52', 'feature_53', 'feature_54',
       'feature_55', 'feature_56', 'feature_57', 'feature_58', 'feature_59',
       'feature_60', 'feature_61', 'feature_62', 'feature_63', 'feature_64',
       'feature_65', 'feature_66', 'feature_67', 'feature_68', 'feature_69',
       'feature_70', 'feature_71', 'feature_72', 'feature_73', 'feature_74'],
      dtype='object')

In [249]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)
test = scaler.transform(test)

In [283]:
model = LogisticRegression(random_state=123 )
model = RandomForestClassifier(n_estimators=500, max_leaf_nodes=3, max_depth=10, random_state=123)
# clf.fit(X_train_valid, y_train_valid)

In [288]:
model.fit(X_train, y_train)
y_pred = model.predict_proba(X_test)

In [289]:
print(y_pred)
print(y_test)
values, counts = np.unique(y_pred, return_counts=True)
print(values)
print(counts)

[[0.04620941 0.12550716 0.07684369 ... 0.07440431 0.2576068  0.13181492]
 [0.04260685 0.07491725 0.05341728 ... 0.08076575 0.29814067 0.11715225]
 [0.04186382 0.06690037 0.04898526 ... 0.080857   0.30474212 0.11366174]
 ...
 [0.05174894 0.22100248 0.11612829 ... 0.06007038 0.18081965 0.14746353]
 [0.04728964 0.15333839 0.08799345 ... 0.06912149 0.23129772 0.13438901]
 [0.04178723 0.06541796 0.04851019 ... 0.08185259 0.30784664 0.1136818 ]]
[0 7 4 ... 3 7 7]
[0.01431471 0.01431894 0.01432231 ... 0.32893876 0.32895335 0.32897025]
[1 1 1 ... 1 1 1]

In [295]:
from sklearn.metrics import log_loss
val = log_loss(y_test,y_pred)
print(val)
# 1.8307023065814374 for LR
# 4.002083813135203 for RC
# 1.8306874700003668 for parameterized RC

1.8306874700003668

In [296]:
sub = pd.read_csv("/kaggle/input/tabular-playground-series-jun-2021/sample_submission.csv")
y_res = model.predict_proba(test)

In [297]:
y_res.shape

(100000, 9)

In [298]:
sub.head(10)
predictions = pd.DataFrame()
predictions["id"] = sub["id"]
predictions = pd.concat([predictions, pd.DataFrame(y_res, columns=["Class_" + str(x) for x in np.arange(1, 10, 1)])], axis=1)
predictions.to_csv('submission.csv', index=False, header=predictions.columns)
predictions.head()

,id,Class_1,Class_2,Class_3,Class_4,Class_5,Class_6,Class_7,Class_8,Class_9
0,200000,0.051676,0.221166,0.116121,0.028054,0.016119,0.180054,0.059696,0.179742,0.147371
1,200001,0.046503,0.139959,0.082038,0.024311,0.015633,0.242347,0.071919,0.245304,0.131986
2,200002,0.044087,0.097585,0.063033,0.022376,0.014929,0.285391,0.076175,0.274474,0.121951
3,200003,0.046061,0.121452,0.073741,0.023923,0.015288,0.258223,0.074077,0.258389,0.128847
4,200004,0.046186,0.135797,0.080278,0.024036,0.015420,0.252922,0.071215,0.243490,0.130656